ALTER TABLE Users 
ADD COLUMN isDeleted bit 
DEFAULT CAST (0 AS BIT) NOT NULL;

ALTER TABLE Users
ADD CONSTRAINT UC_User UNIQUE (token);

ALTER TABLE Users
ADD CONSTRAINT UCID_User UNIQUE (idNumber);

